apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    app: nginx
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  restartPolicy: Always