apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    app: nginx
spec:
  containers:
    - name: nginx
      imagePullPolicy: IfNotPresent
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      #      startupProbe:
      #        httpGet:
      #          path: /successful
      #          port: 80
      #        tcpSocket:
      #          port: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
      livenessProbe:
#        exec:
#          command:
#            - pgrep java
        httpGet:
          httpHeaders:
            - name: auth
              value: wyqq
          port: 1234
          path: /health
        initialDelaySeconds: 3
        successThreshold: 1
        failureThreshold: 1
        timeoutSeconds: 3
        periodSeconds: 6

  restartPolicy: Always

